[hello]
command = "echo hello"

[sleep]
command = "sleep 48590234"

[environment]
command = "echo $HELLO && sleep 37852375"
env = { HELLO = "uwu hi ヾ(•ω•`)o" }

[pwd]
command = "pwd"
workdir = "./src"

[crash]
command = "cat fkasdjfölashjdflksd"

[side-effect-create]
command = "touch uwu.txt"

[side-effect-remove]
command = "rm uwu.txt"

[compile]
command = "cargo check"

[loop]
command = """
counter=0

while true; do
    echo $counter
    counter=$((counter+1))
done
"""